# This is a basic workflow to help you get started with Actions

name: Sync Fork with Upstream

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Fork Sync
        uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          merge_method: squash
          owner: BenHowell71
          head: gh-pages
          base: gh-pages
