on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
        r-version: 4.1.3 

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            pkgdown
            animation
            baseballr
            cfbfastR
            chessR
            hoopR
            ggimage
            knitr
            ragg
            rsconnect
            sportyR
            tictoc
            tidyverse
            toRvik
            wehoop
            zoo
          needs: website
      - name: Install system dependencies
        run: |
          pak::pkg_install("hadley/emo")
          pak::pkg_install("r-lib/pkgapi")
        shell: Rscript {0}

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
